<?php
$xitongurls = [
	'bjssc'   => '/Caiji.Xitong.kenossc.name.bjssc.from.bjkeno',
	'hgssc'   => '/Caiji.Xitong.kenossc.name.hgssc.from.hgkeno',
	'twssc'   => '/Caiji.Xitong.kenossc.name.twssc.from.twkeno',
	'jndssc'  => '/Caiji.Xitong.kenossc.name.jndssc.from.jndkeno',
	'actssc'  => '/Caiji.Xitong.kenossc.name.actssc.from.actkeno',	
	'bj3d'   => '/Caiji.Xitong.keno3d.name.bj3d.from.bjkeno',
	'hg3d'   => '/Caiji.Xitong.keno3d.name.hg3d.from.hgkeno',
	'tw3d'   => '/Caiji.Xitong.keno3d.name.tw3d.from.twkeno',
	'jnd3d'  => '/Caiji.Xitong.keno3d.name.jnd3d.from.jndkeno',
	'act3d'  => '/Caiji.Xitong.keno3d.name.act3d.from.actkeno',	
	'bj28'   => '/Caiji.Xitong.keno28.name.bj28.from.bjkeno',
	'hg28'   => '/Caiji.Xitong.keno28.name.hg28.from.hgkeno',
	'jnd28'   => '/Caiji.Xitong.keno28.name.jnd28.from.jndkeno',
	'tw28'  => '/Caiji.Xitong.keno28.name.tw28.from.twkeno',
	'act28'  => '/Caiji.Xitong.keno28.name.act28.from.actkeno',
	'ffc1'   => '/Caiji.Xitong.xtssc.name.ffc1',
	'ffc2'   => '/Caiji.Xitong.xtssc.name.ffc2',
	'ffc5'   => '/Caiji.Xitong.xtssc.name.ffc5',
	'dfssc' => '/Caiji.Xitong.xtssc.name.dfssc',
    'amssc' => '/Caiji.Xitong.xtssc.name.amssc',
	'f1k3'  => '/Caiji.Xitong.xtk3.name.f1k3',
	'f5k3'  => '/Caiji.Xitong.xtk3.name.f5k3',
	'ffk3'  => '/Caiji.Xitong.xtk3.name.ffk3',
	'df3d'  => '/Caiji.Xitong.xt3d.name.df3d',
	'df11x5'=> '/Caiji.Xitong.xt11x5.name.df11x5',
	'dfpk10'=> '/Caiji.Xitong.xtpk10.name.dfpk10',
    'yfpk10'=> '/Caiji.Xitong.xtpk10.name.yfpk10',
	'dfkeno'=> '/Caiji.Xitong.xtkeno.name.dfkeno',
	'dflhc'   => '/Caiji.Xitong.dflhc.name.dflhc',
	'f111x5'  => '/Caiji.Xitong.xt11x5.name.f111x5',
	'f511x5'  => '/Caiji.Xitong.xt11x5.name.f511x5',
	
	'f10kl10f'  => '/Caiji.Xitong.xtkl10f.name.f10kl10f',
];
