<?php
namespace Lib;
class wanfa {
	//typeid (ssc,k3...)
	function getplayers($typeid){
		$playrules = [];
		$_wfs = $this->$typeid();
		if(!method_exists($this,$typeid)){
			return false;
		}
		foreach($_wfs as $k=>$v){
			foreach($v['list'] as $k1=>$v1){
				$playrules[$v1['playid']] = $v1;
			}
		}
		return $playrules;
	}
	function xy28(){
		$tms = [];
		for($i=0;$i<=27;$i++){
			/*$tm = str_pad($i,2,0,STR_PAD_LEFT);*/
			$tms[] = ['playid'=>'xy28_tm_'.str_pad($i,2,0,STR_PAD_LEFT),'rate'=>1,'title'=>$i];
		}
		$xy28 = [
			'tm'=>[
				'title'=>'特码',
				'list'=>$tms
			],
			'hunhe'=>[
				'title'=>'混合',
				'list'=>[
					['playid'=>'xy28_hunhe_big','rate'=>1,'title'=>'大'],
					['playid'=>'xy28_hunhe_small','rate'=>1,'title'=>'小'],
					['playid'=>'xy28_hunhe_odd','rate'=>1,'title'=>'单'],
					['playid'=>'xy28_hunhe_even','rate'=>1,'title'=>'双'],
					['playid'=>'xy28_hunhe_big_odd','rate'=>1,'title'=>'大单'],
					['playid'=>'xy28_hunhe_small_odd','rate'=>1,'title'=>'小单'],
					['playid'=>'xy28_hunhe_big_even','rate'=>1,'title'=>'大双'],
					['playid'=>'xy28_hunhe_small_even','rate'=>1,'title'=>'小双'],
					['playid'=>'xy28_hunhe_ji_big','rate'=>1,'title'=>'极大'],
					['playid'=>'xy28_hunhe_ji_small','rate'=>1,'title'=>'极小'],
				],
			],
		];
		return $xy28;
	}
	function keno(){
		$zhuzis = [];
		for($i=1;$i<=80;$i++){
			$zhuzi = str_pad($i,2,0,STR_PAD_LEFT);
			$zhuzis[] = ['playid'=>'keno_zhuzi_'.$zhuzi,'title'=>$zhuzi];
		}
		$klc = [
			'rx1'=>[
				'title'=>'任选一',
				'list'=>[
					['playid'=>'bjkl8rx1','rate'=>'1.95','title'=>'任选一'],
				],
			],
			'rx2'=>[
				'title'=>'任选二',
				'list'=>[
					['playid'=>'bjkl8rx2','rate'=>'1.95','title'=>'任选二'],
				],
			],
			'rx3'=>[
				'title'=>'任选三',
				'list'=>[
					['playid'=>'bjkl8rx3','rate'=>'1.95','title'=>'任选三'],
				],
			],
			'rx4'=>[
				'title'=>'任选四',
				'list'=>[
					['playid'=>'bjkl8rx4','rate'=>'1.95','title'=>'任选四'],
				],
			],
			'rx5'=>[
				'title'=>'任选五',
				'list'=>[
					['playid'=>'bjkl8rx5','rate'=>'1.95','title'=>'任选五'],
				],
			],
			'rx6'=>[
				'title'=>'任选六',
				'list'=>[
					['playid'=>'bjkl8rx6','rate'=>'1.95','title'=>'任选六'],
				],
			],
			'rx7'=>[
				'title'=>'任选七',
				'list'=>[
					['playid'=>'bjkl8rx7','rate'=>'1.95','title'=>'任选七'],
				],
			],
			'quw'=>[
				'title'=>'趣味',
				'list'=>[
					['playid'=>'big','rate'=>'1.95','title'=>'大'],
					['playid'=>'bigsmahe','rate'=>'4.3','title'=>'和'],
					['playid'=>'sma','rate'=>'1.95','title'=>'小'],
					['playid'=>'up','rate'=>'1.95','title'=>'上'],
					['playid'=>'mid','rate'=>'4.3','title'=>'中'],
					['playid'=>'down','rate'=>'1.95','title'=>'下'],
					['playid'=>'ji','rate'=>'1.95','title'=>'奇'],
					['playid'=>'jiouhe','rate'=>'4.3','title'=>'和'],
					['playid'=>'ou','rate'=>'1.95','title'=>'偶'],
					['playid'=>'sin','rate'=>'1.95','title'=>'单'],
					['playid'=>'cou','rate'=>'1.95','title'=>'双'],
					['playid'=>'bigsin','rate'=>'3.8','title'=>'大单'],
					['playid'=>'smasin','rate'=>'3.8','title'=>'小单'],
					['playid'=>'bigcou','rate'=>'3.8','title'=>'大双'],
					['playid'=>'smacou','rate'=>'3.8','title'=>'小双'],
					['playid'=>'jin','rate'=>'9.2','title'=>'金'],
					['playid'=>'mu','rate'=>'4.6','title'=>'木'],
					['playid'=>'shui','rate'=>'2.4','title'=>'水'],
					['playid'=>'huo','rate'=>'4.6','title'=>'火'],
					['playid'=>'tu','rate'=>'9.2','title'=>'土'],
				],
			],
			/*'zhuzi'=>[
				'title'=>'珠仔',
				'list'=>$zhuzis
			],*/
		];
		return $klc;
	}
	function lhc(){
		$lhc = [
			'tbha'=>[
				'title'=>'特别号A面',
				'list'=>[
					['playid'=>'lhc_tbha_01','title'=>'01'],
					['playid'=>'lhc_tbha_02','title'=>'02'],
					['playid'=>'lhc_tbha_03','title'=>'03'],
					['playid'=>'lhc_tbha_04','title'=>'04'],
					['playid'=>'lhc_tbha_05','title'=>'05'],
					['playid'=>'lhc_tbha_06','title'=>'06'],
					['playid'=>'lhc_tbha_07','title'=>'07'],
					['playid'=>'lhc_tbha_08','title'=>'08'],
					['playid'=>'lhc_tbha_09','title'=>'09'],
					['playid'=>'lhc_tbha_10','title'=>'10'],
					['playid'=>'lhc_tbha_11','title'=>'11'],
					['playid'=>'lhc_tbha_12','title'=>'12'],
					['playid'=>'lhc_tbha_13','title'=>'13'],
					['playid'=>'lhc_tbha_14','title'=>'14'],
					['playid'=>'lhc_tbha_15','title'=>'15'],
					['playid'=>'lhc_tbha_16','title'=>'16'],
					['playid'=>'lhc_tbha_17','title'=>'17'],
					['playid'=>'lhc_tbha_18','title'=>'18'],
					['playid'=>'lhc_tbha_19','title'=>'19'],
					['playid'=>'lhc_tbha_20','title'=>'20'],
					['playid'=>'lhc_tbha_21','title'=>'21'],
					['playid'=>'lhc_tbha_22','title'=>'22'],
					['playid'=>'lhc_tbha_23','title'=>'23'],
					['playid'=>'lhc_tbha_24','title'=>'24'],
					['playid'=>'lhc_tbha_25','title'=>'25'],
					['playid'=>'lhc_tbha_26','title'=>'26'],
					['playid'=>'lhc_tbha_27','title'=>'27'],
					['playid'=>'lhc_tbha_28','title'=>'28'],
					['playid'=>'lhc_tbha_29','title'=>'29'],
					['playid'=>'lhc_tbha_30','title'=>'30'],
					['playid'=>'lhc_tbha_31','title'=>'31'],
					['playid'=>'lhc_tbha_32','title'=>'32'],
					['playid'=>'lhc_tbha_33','title'=>'33'],
					['playid'=>'lhc_tbha_34','title'=>'34'],
					['playid'=>'lhc_tbha_35','title'=>'35'],
					['playid'=>'lhc_tbha_36','title'=>'36'],
					['playid'=>'lhc_tbha_37','title'=>'37'],
					['playid'=>'lhc_tbha_38','title'=>'38'],
					['playid'=>'lhc_tbha_39','title'=>'39'],
					['playid'=>'lhc_tbha_40','title'=>'40'],
					['playid'=>'lhc_tbha_41','title'=>'41'],
					['playid'=>'lhc_tbha_42','title'=>'42'],
					['playid'=>'lhc_tbha_43','title'=>'43'],
					['playid'=>'lhc_tbha_44','title'=>'44'],
					['playid'=>'lhc_tbha_45','title'=>'45'],
					['playid'=>'lhc_tbha_46','title'=>'46'],
					['playid'=>'lhc_tbha_47','title'=>'47'],
					['playid'=>'lhc_tbha_48','title'=>'48'],
					['playid'=>'lhc_tbha_49','title'=>'49'],
					['playid'=>'lhc_tbha_t_big','title'=>'特大'],
					['playid'=>'lhc_tbha_t_small','title'=>'特小'],
					['playid'=>'lhc_tbha_t_odd','title'=>'特单'],
					['playid'=>'lhc_tbha_t_even','title'=>'特双'],
					['playid'=>'lhc_tbha_h_big','title'=>'和大'],
					['playid'=>'lhc_tbha_h_small','title'=>'和小'],
					['playid'=>'lhc_tbha_h_odd','title'=>'和单'],
					['playid'=>'lhc_tbha_h_even','title'=>'和双'],
					['playid'=>'lhc_tbha_tw_big','title'=>'特尾大'],
					['playid'=>'lhc_tbha_tw_small','title'=>'特尾小'],
					['playid'=>'lhc_tbha_big_odd','title'=>'大单'],
					['playid'=>'lhc_tbha_big_even','title'=>'大双'],
					['playid'=>'lhc_tbha_small_odd','title'=>'小单'],
					['playid'=>'lhc_tbha_small_even','title'=>'小双'],
				],
			],
			'tbhb'=>[
				'title'=>'特别号B面',
				'list'=>[
					['playid'=>'lhc_tbhb_01','title'=>'01'],
					['playid'=>'lhc_tbhb_02','title'=>'02'],
					['playid'=>'lhc_tbhb_03','title'=>'03'],
					['playid'=>'lhc_tbhb_04','title'=>'04'],
					['playid'=>'lhc_tbhb_05','title'=>'05'],
					['playid'=>'lhc_tbhb_06','title'=>'06'],
					['playid'=>'lhc_tbhb_07','title'=>'07'],
					['playid'=>'lhc_tbhb_08','title'=>'08'],
					['playid'=>'lhc_tbhb_09','title'=>'09'],
					['playid'=>'lhc_tbhb_10','title'=>'10'],
					['playid'=>'lhc_tbhb_11','title'=>'11'],
					['playid'=>'lhc_tbhb_12','title'=>'12'],
					['playid'=>'lhc_tbhb_13','title'=>'13'],
					['playid'=>'lhc_tbhb_14','title'=>'14'],
					['playid'=>'lhc_tbhb_15','title'=>'15'],
					['playid'=>'lhc_tbhb_16','title'=>'16'],
					['playid'=>'lhc_tbhb_17','title'=>'17'],
					['playid'=>'lhc_tbhb_18','title'=>'18'],
					['playid'=>'lhc_tbhb_19','title'=>'19'],
					['playid'=>'lhc_tbhb_20','title'=>'20'],
					['playid'=>'lhc_tbhb_21','title'=>'21'],
					['playid'=>'lhc_tbhb_22','title'=>'22'],
					['playid'=>'lhc_tbhb_23','title'=>'23'],
					['playid'=>'lhc_tbhb_24','title'=>'24'],
					['playid'=>'lhc_tbhb_25','title'=>'25'],
					['playid'=>'lhc_tbhb_26','title'=>'26'],
					['playid'=>'lhc_tbhb_27','title'=>'27'],
					['playid'=>'lhc_tbhb_28','title'=>'28'],
					['playid'=>'lhc_tbhb_29','title'=>'29'],
					['playid'=>'lhc_tbhb_30','title'=>'30'],
					['playid'=>'lhc_tbhb_31','title'=>'31'],
					['playid'=>'lhc_tbhb_32','title'=>'32'],
					['playid'=>'lhc_tbhb_33','title'=>'33'],
					['playid'=>'lhc_tbhb_34','title'=>'34'],
					['playid'=>'lhc_tbhb_35','title'=>'35'],
					['playid'=>'lhc_tbhb_36','title'=>'36'],
					['playid'=>'lhc_tbhb_37','title'=>'37'],
					['playid'=>'lhc_tbhb_38','title'=>'38'],
					['playid'=>'lhc_tbhb_39','title'=>'39'],
					['playid'=>'lhc_tbhb_40','title'=>'40'],
					['playid'=>'lhc_tbhb_41','title'=>'41'],
					['playid'=>'lhc_tbhb_42','title'=>'42'],
					['playid'=>'lhc_tbhb_43','title'=>'43'],
					['playid'=>'lhc_tbhb_44','title'=>'44'],
					['playid'=>'lhc_tbhb_45','title'=>'45'],
					['playid'=>'lhc_tbhb_46','title'=>'46'],
					['playid'=>'lhc_tbhb_47','title'=>'47'],
					['playid'=>'lhc_tbhb_48','title'=>'48'],
					['playid'=>'lhc_tbhb_49','title'=>'49'],
					['playid'=>'lhc_tbhb_t_big','title'=>'特大'],
					['playid'=>'lhc_tbhb_t_small','title'=>'特小'],
					['playid'=>'lhc_tbhb_t_odd','title'=>'特单'],
					['playid'=>'lhc_tbhb_t_even','title'=>'特双'],
					['playid'=>'lhc_tbhb_h_big','title'=>'和大'],
					['playid'=>'lhc_tbhb_h_small','title'=>'和小'],
					['playid'=>'lhc_tbhb_h_odd','title'=>'和单'],
					['playid'=>'lhc_tbhb_h_even','title'=>'和双'],
					['playid'=>'lhc_tbhb_tw_big','title'=>'特尾大'],
					['playid'=>'lhc_tbhb_tw_small','title'=>'特尾小'],
					['playid'=>'lhc_tbhb_big_odd','title'=>'大单'],
					['playid'=>'lhc_tbhb_big_even','title'=>'大双'],
					['playid'=>'lhc_tbhb_small_odd','title'=>'小单'],
					['playid'=>'lhc_tbhb_small_even','title'=>'小双'],
				],
			],
			'sxtw'=>[
				'title'=>'生肖头尾',
				'list'=>[
					['playid'=>'lhc_sxtw_shu','title'=>'鼠'],
					['playid'=>'lhc_sxtw_niu','title'=>'牛'],
					['playid'=>'lhc_sxtw_hu','title'=>'虎'],
					['playid'=>'lhc_sxtw_tu','title'=>'兔'],
					['playid'=>'lhc_sxtw_long','title'=>'龙'],
					['playid'=>'lhc_sxtw_she','title'=>'蛇'],
					['playid'=>'lhc_sxtw_ma','title'=>'马'],
					['playid'=>'lhc_sxtw_yang','title'=>'羊'],
					['playid'=>'lhc_sxtw_hou','title'=>'猴'],
					['playid'=>'lhc_sxtw_ji','title'=>'鸡'],
					['playid'=>'lhc_sxtw_gou','title'=>'狗'],
					['playid'=>'lhc_sxtw_zhu','title'=>'猪'],
					['playid'=>'lhc_sxtw_0t','title'=>'0头'],
					['playid'=>'lhc_sxtw_1t','title'=>'1头'],
					['playid'=>'lhc_sxtw_2t','title'=>'2头'],
					['playid'=>'lhc_sxtw_3t','title'=>'3头'],
					['playid'=>'lhc_sxtw_4t','title'=>'4头'],
					['playid'=>'lhc_sxtw_0w','title'=>'0尾'],
					['playid'=>'lhc_sxtw_1w','title'=>'1尾'],
					['playid'=>'lhc_sxtw_2w','title'=>'2尾'],
					['playid'=>'lhc_sxtw_3w','title'=>'3尾'],
					['playid'=>'lhc_sxtw_4w','title'=>'4尾'],
					['playid'=>'lhc_sxtw_5w','title'=>'5尾'],
					['playid'=>'lhc_sxtw_6w','title'=>'6尾'],
					['playid'=>'lhc_sxtw_7w','title'=>'7尾'],
					['playid'=>'lhc_sxtw_8w','title'=>'8尾'],
					['playid'=>'lhc_sxtw_9w','title'=>'9尾'],
				],
			],
			'bose'=>[
				'title'=>'波色',
				'list'=>[
					['playid'=>'lhc_bose_hong','title'=>'红波'],
					['playid'=>'lhc_bose_lan','title'=>'蓝波'],
					['playid'=>'lhc_bose_lv','title'=>'绿波'],
					['playid'=>'lhc_bose_hong_big','title'=>'红大'],
					['playid'=>'lhc_bose_hong_small','title'=>'红小'],
					['playid'=>'lhc_bose_hong_odd','title'=>'红单'],
					['playid'=>'lhc_bose_hong_even','title'=>'红双'],
					['playid'=>'lhc_bose_lan_big','title'=>'蓝大'],
					['playid'=>'lhc_bose_lan_small','title'=>'蓝小'],
					['playid'=>'lhc_bose_lan_odd','title'=>'蓝单'],
					['playid'=>'lhc_bose_lan_even','title'=>'蓝双'],
					['playid'=>'lhc_bose_lv_big','title'=>'绿大'],
					['playid'=>'lhc_bose_lv_small','title'=>'绿小'],
					['playid'=>'lhc_bose_lv_odd','title'=>'绿单'],
					['playid'=>'lhc_bose_lv_even','title'=>'绿双'],
					['playid'=>'lhc_bose_hong_big_odd','title'=>'红大单'],
					['playid'=>'lhc_bose_hong_big_even','title'=>'红大双'],
					['playid'=>'lhc_bose_hong_small_odd','title'=>'红小单'],
					['playid'=>'lhc_bose_hong_small_even','title'=>'红小双'],
					['playid'=>'lhc_bose_lan_big_odd','title'=>'蓝大单'],
					['playid'=>'lhc_bose_lan_big_even','title'=>'蓝大双'],
					['playid'=>'lhc_bose_lan_small_odd','title'=>'蓝小单'],
					['playid'=>'lhc_bose_lan_small_even','title'=>'蓝小双'],
					['playid'=>'lhc_bose_lv_big_odd','title'=>'绿大单'],
					['playid'=>'lhc_bose_lv_big_even','title'=>'绿大双'],
					['playid'=>'lhc_bose_lv_small_odd','title'=>'绿小单'],
					['playid'=>'lhc_bose_lv_small_even','title'=>'绿小双'],
				],
			],
			'zxbz'=>[
				'title'=>'自选不中',
				'list'=>[
					['playid'=>'lhc_zxbz_bz5','title'=>'五不中'],
					['playid'=>'lhc_zxbz_bz6','title'=>'六不中'],
					['playid'=>'lhc_zxbz_bz7','title'=>'七不中'],
					['playid'=>'lhc_zxbz_bz8','title'=>'八不中'],
					['playid'=>'lhc_zxbz_bz9','title'=>'九不中'],
					['playid'=>'lhc_zxbz_bz10','title'=>'十不中'],
					['playid'=>'lhc_zxbz_bz11','title'=>'十一不中'],
					['playid'=>'lhc_zxbz_bz12','title'=>'十二不中'],
				],
			],
			'ptxw'=>[
				'title'=>'平特肖尾',
				'list'=>[
					['playid'=>'lhc_ptxw_shu','title'=>'鼠'],
					['playid'=>'lhc_ptxw_niu','title'=>'牛'],
					['playid'=>'lhc_ptxw_hu','title'=>'虎'],
					['playid'=>'lhc_ptxw_tu','title'=>'兔'],
					['playid'=>'lhc_ptxw_long','title'=>'龙'],
					['playid'=>'lhc_ptxw_she','title'=>'蛇'],
					['playid'=>'lhc_ptxw_ma','title'=>'马'],
					['playid'=>'lhc_ptxw_yang','title'=>'羊'],
					['playid'=>'lhc_ptxw_hou','title'=>'猴'],
					['playid'=>'lhc_ptxw_ji','title'=>'鸡'],
					['playid'=>'lhc_ptxw_gou','title'=>'狗'],
					['playid'=>'lhc_ptxw_zhu','title'=>'猪'],
					['playid'=>'lhc_ptxw_0w','title'=>'0尾'],
					['playid'=>'lhc_ptxw_1w','title'=>'1尾'],
					['playid'=>'lhc_ptxw_2w','title'=>'2尾'],
					['playid'=>'lhc_ptxw_3w','title'=>'3尾'],
					['playid'=>'lhc_ptxw_4w','title'=>'4尾'],
					['playid'=>'lhc_ptxw_5w','title'=>'5尾'],
					['playid'=>'lhc_ptxw_6w','title'=>'6尾'],
					['playid'=>'lhc_ptxw_7w','title'=>'7尾'],
					['playid'=>'lhc_ptxw_8w','title'=>'8尾'],
					['playid'=>'lhc_ptxw_9w','title'=>'9尾'],
				],
			],
			'lx'=>[
				'title'=>'连肖',
				'list'=>[
					['playid'=>'lhc_lx_p2','title'=>'二肖碰'],
					['playid'=>'lhc_lx_p3','title'=>'三肖碰'],
					['playid'=>'lhc_lx_p4','title'=>'四肖碰'],
					['playid'=>'lhc_lx_p5','title'=>'五肖碰'],
				],
			],
			'lw'=>[
				'title'=>'连尾',
				'list'=>[
					['playid'=>'lhc_lw_p2','title'=>'二尾碰'],
					['playid'=>'lhc_lw_p3','title'=>'三尾碰'],
					['playid'=>'lhc_lw_p4','title'=>'四尾碰'],
					['playid'=>'lhc_lw_p5','title'=>'五尾碰'],
				],
			],
			'lm'=>[
				'title'=>'连码',
				'list'=>[
					['playid'=>'lhc_lm_qz4','title'=>'四全中'],
					['playid'=>'lhc_lm_qz3','title'=>'三全中'],
					['playid'=>'lhc_lm_3z2','title'=>'三中二'],
					['playid'=>'lhc_lm_3z3','title'=>'三中三'],
					['playid'=>'lhc_lm_2z2','title'=>'二中二'],
					['playid'=>'lhc_lm_2zt','title'=>'二中特[中特]'],
					['playid'=>'lhc_lm_2ztz2','title'=>'二中特[中二]'],
					['playid'=>'lhc_lm_tc','title'=>'特串'],
				],
			],
			'zmpm'=>[
				'title'=>'正码平码',
				'list'=>[
					['playid'=>'lhc_zmpm_01','title'=>'01'],
					['playid'=>'lhc_zmpm_02','title'=>'02'],
					['playid'=>'lhc_zmpm_03','title'=>'03'],
					['playid'=>'lhc_zmpm_04','title'=>'04'],
					['playid'=>'lhc_zmpm_05','title'=>'05'],
					['playid'=>'lhc_zmpm_06','title'=>'06'],
					['playid'=>'lhc_zmpm_07','title'=>'07'],
					['playid'=>'lhc_zmpm_08','title'=>'08'],
					['playid'=>'lhc_zmpm_09','title'=>'09'],
					['playid'=>'lhc_zmpm_10','title'=>'10'],
					['playid'=>'lhc_zmpm_11','title'=>'11'],
					['playid'=>'lhc_zmpm_12','title'=>'12'],
					['playid'=>'lhc_zmpm_13','title'=>'13'],
					['playid'=>'lhc_zmpm_14','title'=>'14'],
					['playid'=>'lhc_zmpm_15','title'=>'15'],
					['playid'=>'lhc_zmpm_16','title'=>'16'],
					['playid'=>'lhc_zmpm_17','title'=>'17'],
					['playid'=>'lhc_zmpm_18','title'=>'18'],
					['playid'=>'lhc_zmpm_19','title'=>'19'],
					['playid'=>'lhc_zmpm_20','title'=>'20'],
					['playid'=>'lhc_zmpm_21','title'=>'21'],
					['playid'=>'lhc_zmpm_22','title'=>'22'],
					['playid'=>'lhc_zmpm_23','title'=>'23'],
					['playid'=>'lhc_zmpm_24','title'=>'24'],
					['playid'=>'lhc_zmpm_25','title'=>'25'],
					['playid'=>'lhc_zmpm_26','title'=>'26'],
					['playid'=>'lhc_zmpm_27','title'=>'27'],
					['playid'=>'lhc_zmpm_28','title'=>'28'],
					['playid'=>'lhc_zmpm_29','title'=>'29'],
					['playid'=>'lhc_zmpm_30','title'=>'30'],
					['playid'=>'lhc_zmpm_31','title'=>'31'],
					['playid'=>'lhc_zmpm_32','title'=>'32'],
					['playid'=>'lhc_zmpm_33','title'=>'33'],
					['playid'=>'lhc_zmpm_34','title'=>'34'],
					['playid'=>'lhc_zmpm_35','title'=>'35'],
					['playid'=>'lhc_zmpm_36','title'=>'36'],
					['playid'=>'lhc_zmpm_37','title'=>'37'],
					['playid'=>'lhc_zmpm_38','title'=>'38'],
					['playid'=>'lhc_zmpm_39','title'=>'39'],
					['playid'=>'lhc_zmpm_40','title'=>'40'],
					['playid'=>'lhc_zmpm_41','title'=>'41'],
					['playid'=>'lhc_zmpm_42','title'=>'42'],
					['playid'=>'lhc_zmpm_43','title'=>'43'],
					['playid'=>'lhc_zmpm_44','title'=>'44'],
					['playid'=>'lhc_zmpm_45','title'=>'45'],
					['playid'=>'lhc_zmpm_46','title'=>'46'],
					['playid'=>'lhc_zmpm_47','title'=>'47'],
					['playid'=>'lhc_zmpm_48','title'=>'48'],
					['playid'=>'lhc_zmpm_49','title'=>'49'],
					['playid'=>'lhc_zmpm_big','title'=>'总大'],
					['playid'=>'lhc_zmpm_small','title'=>'总小'],
					['playid'=>'lhc_zmpm_odd','title'=>'总单'],
					['playid'=>'lhc_zmpm_even','title'=>'总双'],
				],
			],
		];
		return $lhc;
	}
	function dpc(){
		$dp3 = [
			'x3'=>[
				'title'=>'直选',
				'list'=>[
					['playid'=>'pl3zxfs','title'=>'三星直选复式'],
					['playid'=>'pl3zxds','title'=>'三星直选单式'],
				],
			],
			'zx'=>[
				'title'=>'组选',
				'list'=>[
					['playid'=>'pl3zux3','title'=>'三星组三'],
					['playid'=>'pl3zux6','title'=>'三星组六'],
					['playid'=>'pl3zuxhh','title'=>'三星混合'],
					['playid'=>'pl3zux3dt','title'=>'三星组三拖胆'],
					['playid'=>'pl3zux6dt','title'=>'三星组六拖胆'],
				],
			],
			'x2'=>[
				'title'=>'二星',
				'list'=>[
					['playid'=>'pl3qx2fs','title'=>'前二直选复式'],
					['playid'=>'pl3qx2ds','title'=>'前二直选单式'],
					['playid'=>'pl3hx2fs','title'=>'后二直选复式'],
					['playid'=>'pl3hx2ds','title'=>'后二直选单式'],
				],
			],
			'bdw'=>[
				'title'=>'不定位胆',
				'list'=>[
					['playid'=>'pl3bdw','title'=>'不定位'],
				],
			],
			'dw'=>[
				'title'=>'定位胆',
				'list'=>[
					['playid'=>'pl3dwd1q','title'=>'前一'],
					['playid'=>'pl3dwd1z','title'=>'中一'],
					['playid'=>'pl3dwd1h','title'=>'后一'],
				],
			],
			'hz'=>[
				'title'=>'和值',
				'list'=>[
					['playid'=>'pl3hzzx','title'=>'和值直选'],
					['playid'=>'pl3hzzux3','title'=>'和值组三'],
					['playid'=>'pl3hzzux6','title'=>'和值组六'],
					['playid'=>'pl3hzdx','title'=>'和值大小'],
				],
			],
			'quw'=>[
				'title'=>'趣味',
				'list'=>[
					['playid'=>'pl3qwjo','title'=>'趣味奇偶'],
					['playid'=>'pl3qwtlj','title'=>'趣味拖拉机'],
				],
			],
		];
		return $dp3;
	}
	function pk10(){
		$pk10 = [
			'qian1'=>[
				'title'=>'前一',
				'list'=>[
					['playid'=>'bjpk10qian1','title'=>'前一复式'],
				],
			],
			'qian2'=>[
				'title'=>'前二',
				'list'=>[
					['playid'=>'bjpk10qian2','title'=>'前二复式'],
					['playid'=>'bjpk10qian2ds','title'=>'前二单式'],
				],
			],
			'qian3'=>[
				'title'=>'前三',
				'list'=>[
					['playid'=>'bjpk10qian3','title'=>'前三复式'],
					['playid'=>'bjpk10qian3ds','title'=>'前三单式'],
				],
			],
			'qian4'=>[
				'title'=>'前四',
				'list'=>[
					['playid'=>'bjpk10qian4','title'=>'前四复式'],
					['playid'=>'bjpk10qian4ds','title'=>'前四单式'],
				],
			],
			'qian5'=>[
				'title'=>'前五',
				'list'=>[
					['playid'=>'bjpk10qian5','title'=>'前五复式'],
					['playid'=>'bjpk10qian5ds','title'=>'前五单式'],
				],
			],
			'dwd'=>[
				'title'=>'定位胆',
				'list'=>[
					['playid'=>'bjpk10dwd','title'=>'定位胆'],
				],
			],
			'dx'=>[
				'title'=>'大小',
				'list'=>[
					['playid'=>'bjpk10dxdy','title'=>'第一名'],
					['playid'=>'bjpk10dxde','title'=>'第二名'],
					['playid'=>'bjpk10dxds','title'=>'第三名'],
				],
			],
			'ds'=>[
				'title'=>'单双',
				'list'=>[
					['playid'=>'bjpk10dsdy','title'=>'第一名'],
					['playid'=>'bjpk10dsde','title'=>'第二名'],
					['playid'=>'bjpk10dsds','title'=>'第三名'],
				],
			],
			'lh'=>[
				'title'=>'龙虎',
				'list'=>[
					['playid'=>'bjpk10lhdy','title'=>'第一名'],
					['playid'=>'bjpk10lhde','title'=>'第二名'],
					['playid'=>'bjpk10lhds','title'=>'第三名'],
				],
			],
		];
		return $pk10;
	}
	function k3(){
		$k3 = [
			'ethfx'=>[
				'title'=>'二同号复选',
				'list'=>[
					['playid'=>'k3ethfx','rate'=>'60','title'=>'二同号复选'],
				],
			],
			'ethdx'=>[
				'title'=>'二同号单选',
				'list'=>[
					['playid'=>'k3ethdx','rate'=>'60','title'=>'二同号单选'],
				],
			],
			'ebth'=>[
				'title'=>'二不同号',
				'list'=>[
					['playid'=>'k3ebthbz','rate'=>'6.5','title'=>'二不同号'],
				],
			],
			'sthdx'=>[
				'title'=>'三同号单选',
				'list'=>[
					['playid'=>'k3sthdx','rate'=>'180','title'=>'三同号单选'],
				],
			],
			'sthtx'=>[
				'title'=>'三同号通选',
				'list'=>[
					['playid'=>'k3sthtx','rate'=>'36.5','title'=>'三同号通选'],
				],
			],
			'sbth'=>[
				'title'=>'三不同号',
				'list'=>[
					['playid'=>'k3sbthbz','rate'=>'32.5','title'=>'三不同号'],
				],
			],
			'slhtx'=>[
				'title'=>'三连号通选',
				'list'=>[
					['playid'=>'k3slhtx','rate'=>'8.5','title'=>'三连号通选'],
				],
			],
			'slhdx'=>[
				'title'=>'三连号单选',
				'list'=>[
					['playid'=>'k3slhdx','rate'=>'8.5','title'=>'三连号单选'],
				],
			],
			'k3hzzx'=>[
				'title'=>'和值',
				'list'=>[
					
					['playid'=>'k3hz3','rate'=>'180','title'=>'3'],
					['playid'=>'k3hz4','rate'=>'60','title'=>'4'],
					['playid'=>'k3hz5','rate'=>'32.5','title'=>'5'],
					['playid'=>'k3hz6','rate'=>'20.5','title'=>'6'],
					['playid'=>'k3hz7','rate'=>'12.5','title'=>'7'],
					['playid'=>'k3hz8','rate'=>'9.5','title'=>'8'],
					['playid'=>'k3hz9','rate'=>'8.5','title'=>'9'],
					['playid'=>'k3hz10','rate'=>'7.5','title'=>'10'],
					['playid'=>'k3hz11','rate'=>'7.5','title'=>'11'],
					['playid'=>'k3hz12','rate'=>'8.5','title'=>'12'],
					['playid'=>'k3hz13','rate'=>'9.5','title'=>'13'],
					['playid'=>'k3hz14','rate'=>'12.5','title'=>'14'],
					['playid'=>'k3hz15','rate'=>'20.5','title'=>'15'],
					['playid'=>'k3hz16','rate'=>'32.5','title'=>'16'],
					['playid'=>'k3hz17','rate'=>'60','title'=>'17'],
					['playid'=>'k3hz18','rate'=>'180','title'=>'18'],
					['playid'=>'k3hzbig','rate'=>'1.95','title'=>'大'],
					['playid'=>'k3hzsmall','rate'=>'1.95','title'=>'小'],
					['playid'=>'k3hzodd','rate'=>'1.95','title'=>'单'],
					['playid'=>'k3hzeven','rate'=>'1.95','title'=>'双'],
				],
			],
		];
		return $k3;
	}
	function x5(){
		$x5 = [
			'sx'=>[
				'title'=>'三星',
				'list'=>[
					['playid'=>'x5qsfs','title'=>'前三直选复式'],
					['playid'=>'x5qsds','title'=>'前三直选单式'],
					['playid'=>'x5zsfs','title'=>'中三直选复式'],
					['playid'=>'x5zsds','title'=>'中三直选单式'],
					['playid'=>'x5hsfs','title'=>'后三直选复式'],
					['playid'=>'x5hsds','title'=>'后三直选单式'],
					
					['playid'=>'x5qszx','title'=>'前三组选复式'],
					['playid'=>'x5qsdt','title'=>'前三组选胆拖'],
					['playid'=>'x5zszx','title'=>'中三组选复式'],
					['playid'=>'x5zsdt','title'=>'中三组选胆拖'],
					['playid'=>'x5hszx','title'=>'后三组选复式'],
					['playid'=>'x5hsdt','title'=>'后三组选胆拖'],
					
				],
			],
			'ex'=>[
				'title'=>'二星',
				'list'=>[
					['playid'=>'x5qefs','title'=>'前二直选复式'],
					['playid'=>'x5qeds','title'=>'前二直选单式'],
					['playid'=>'x5hefs','title'=>'后二直选复式'],
					['playid'=>'x5heds','title'=>'后二直选单式'],
					['playid'=>'x5qezx','title'=>'前二组选复式'],
					['playid'=>'x5qedt','title'=>'前二组选胆拖'],
					['playid'=>'x5hezx','title'=>'后二组选复式'],
					['playid'=>'x5hedt','title'=>'后二组选胆拖'],
				],
			],
			'bdw'=>[
				'title'=>'不定位',
				'list'=>[
					['playid'=>'x5bdwqs','title'=>'前三不定位'],
					['playid'=>'x5bdwzs','title'=>'中三不定位'],
					['playid'=>'x5bdwhs','title'=>'后三不定位'],
				],
			],
			'dw'=>[
				'title'=>'定位胆',
				'list'=>[
					['playid'=>'x5dwd','title'=>'定位胆'],
				],
			],
			
			'rx'=>[
				'title'=>'任选',
				'list'=>[
					['playid'=>'x5rx1z1','title'=>'任选复式一中一'],
					['playid'=>'x5rx2z2','title'=>'任选复式二中二'],
					['playid'=>'x5rx3z3','title'=>'任选复式三中三'],
					['playid'=>'x5rx4z4','title'=>'任选复式四中四'],
					['playid'=>'x5rx5z5','title'=>'任选复式五中五'],
					['playid'=>'x5rx6z5','title'=>'任选复式六中五'],
					['playid'=>'x5rx7z5','title'=>'任选复式七中五'],
					['playid'=>'x5rx8z5','title'=>'任选复式八中五'],
					
					['playid'=>'x5rxds1z1','title'=>'任选单式一中一'],
					['playid'=>'x5rxds2z2','title'=>'任选单式二中二'],
					['playid'=>'x5rxds3z3','title'=>'任选单式三中三'],
					['playid'=>'x5rxds4z4','title'=>'任选单式四中四'],
					['playid'=>'x5rxds5z5','title'=>'任选单式五中五'],
					['playid'=>'x5rxds6z5','title'=>'任选单式六中五'],
					['playid'=>'x5rxds7z5','title'=>'任选单式七中五'],
					['playid'=>'x5rxds8z5','title'=>'任选单式八中五'],
				],
			],
			
			'dt'=>[
				'title'=>'胆拖',
				'list'=>[
					['playid'=>'x5dt2z2','title'=>'胆拖二中二'],
					['playid'=>'x5dt3z3','title'=>'胆拖三中三'],
					['playid'=>'x5dt4z4','title'=>'胆拖四中四'],
					['playid'=>'x5dt5z5','title'=>'胆拖五中五'],
					['playid'=>'x5dt6z5','title'=>'胆拖六中五'],
					['playid'=>'x5dt7z5','title'=>'胆拖七中五'],
					['playid'=>'x5dt8z5','title'=>'胆拖八中五'],
				],
			],
			'quw'=>[
				'title'=>'趣味型',
				'list'=>[
					['playid'=>'x5dds','title'=>'定单双'],
					['playid'=>'x5czw','title'=>'猜中位'],
				],
			],
		];
		return $x5;
	}
	function ssc(){
		$ssc = [
			'5x'=>[
				'title'=>'五星',
				'list'=>[
					['playid'=>'wxzhixfs','title'=>'五星复式'],
					['playid'=>'wxzhixds','title'=>'五星单式'],
					['playid'=>'wxzxyel','title'=>'组选120'],
					['playid'=>'wxzxls','title'=>'组选60'],
					['playid'=>'wxzxsl','title'=>'组选30'],
					['playid'=>'wxzxel','title'=>'组选20'],
					['playid'=>'wxzxyl','title'=>'组选10'],
					['playid'=>'wxzxw','title'=>'组选5'],
				],
			],
			'q4x'=>[
				'title'=>'前四',
				'list'=>[
					['playid'=>'sixzhixfsq','title'=>'前四复式'],
					['playid'=>'sixzhixdsq','title'=>'前四单式'],
					['playid'=>'qsizxes','title'=>'前四组选24'],
					['playid'=>'qsizxye','title'=>'前四组选12'],
					['playid'=>'qsizxl','title'=>'前四组选6'],
					['playid'=>'qsizxs','title'=>'前四组选4'],
				],
			],
			'h4x'=>[
				'title'=>'后四',
				'list'=>[
					['playid'=>'sixzhixfsh','title'=>'后四复式'],
					['playid'=>'sixzhixdsh','title'=>'后四单式'],
					['playid'=>'hsizxes','title'=>'后四组选24'],
					['playid'=>'hsizxye','title'=>'后四组选12'],
					['playid'=>'hsizxl','title'=>'后四组选6'],
					['playid'=>'hsizxs','title'=>'后四组选4'],
				],
			],
			'q3x'=>[
				'title'=>'前三',
				'list'=>[
					['playid'=>'sxzhixfsq','title'=>'前三复式'],
					['playid'=>'sxzhixdsq','title'=>'前三单式'],
					['playid'=>'sxzuxzsq','title'=>'组三'],
					['playid'=>'sxzuxzsdtq','title'=>'组三胆拖'],
					['playid'=>'sxzuxzlq','title'=>'组六'],
					['playid'=>'sxzuxzldtq','title'=>'组六胆拖'],
					['playid'=>'sxhhzxq','title'=>'混合组选'],
					['playid'=>'qszsds','title'=>'前三组三单式'],
					['playid'=>'qszlds','title'=>'前三组六单式'],
				],
			],
			'z3x'=>[
				'title'=>'中三',
				'list'=>[
					['playid'=>'sxzhixfsz','title'=>'中三复式'],
					['playid'=>'sxzhixdsz','title'=>'中三单式'],
					['playid'=>'sxzuxzsz','title'=>'组三'],
					['playid'=>'sxzuxzsdtz','title'=>'组三胆拖'],
					['playid'=>'sxzuxzlz','title'=>'组六'],
					['playid'=>'sxzuxzldtz','title'=>'组六胆拖'],
					['playid'=>'sxhhzxz','title'=>'混合组选'],
					['playid'=>'zszsds','title'=>'中三组三单式'],
					['playid'=>'zszlds','title'=>'中三组六单式'],
				],
			],
			'h3x'=>[
				'title'=>'后三',
				'list'=>[
					['playid'=>'sxzhixfsh','title'=>'后三复式'],
					['playid'=>'sxzhixdsh','title'=>'后三单式'],
					['playid'=>'sxzuxzsh','title'=>'组三'],
					['playid'=>'sxzuxzsdth','title'=>'组三胆拖'],
					['playid'=>'sxzuxzlh','title'=>'组六'],
					['playid'=>'sxzuxzldth','title'=>'组六胆拖'],
					['playid'=>'sxhhzxh','title'=>'混合组选'],
					['playid'=>'hszsds','title'=>'后三组三单式'],
					['playid'=>'hszlds','title'=>'后三组六单式'],
				],
			],
			'2x'=>[
				'title'=>'二星',
				'list'=>[
					['playid'=>'exzhixfsq','title'=>'前二直选复式'],
					['playid'=>'exzhixdsq','title'=>'前二直选单式'],
					['playid'=>'exzhixfsh','title'=>'后二直选复式'],
					['playid'=>'exzhixdsh','title'=>'后二直选单式'],
					['playid'=>'exzuxfsq','title'=>'前二组选复式'],
					['playid'=>'exzuxdsq','title'=>'前二组选单式'],
					['playid'=>'exzuxfsh','title'=>'后二组选复式'],
					['playid'=>'exzuxdsh','title'=>'后二组选单式'],
				],
			],
			'dw'=>[
				'title'=>'定位胆',
				'list'=>[
					['playid'=>'dweid','title'=>'一星复式'],
					['playid'=>'zuxcsbd','title'=>'前三组选包胆'],
					['playid'=>'zuxzsbd','title'=>'中三组选包胆'],
					['playid'=>'zuxhsbd','title'=>'后三组选包胆'],
					['playid'=>'zuxcebd','title'=>'前二组选包胆'],
					['playid'=>'zuxhebd','title'=>'后二组选包胆'],
				],
			],
			'bdw'=>[
				'title'=>'不定位',
				'list'=>[
					['playid'=>'bdwqs','title'=>'前三不定位'],
					['playid'=>'bdwzs','title'=>'中三不定位'],
					['playid'=>'bdwhs','title'=>'后三不定位'],
					['playid'=>'bdw5x1m','title'=>'五星一码不定位'],
					['playid'=>'bdw5x2m','title'=>'五星二码不定位'],
					['playid'=>'bdw5x3m','title'=>'五星三码不定位'],
					['playid'=>'bdw4x1m','title'=>'四星一码不定位'],
					['playid'=>'bdw4x2m','title'=>'四星二码不定位'],
					['playid'=>'bdwqs2m','title'=>'前三二码不定位'],
					['playid'=>'bdwzs2m','title'=>'中三二码不定位'],
					['playid'=>'bdwhs2m','title'=>'后三二码不定位'],
					['playid'=>'bdw2mjc','title'=>'二码计重'],
					['playid'=>'bdw3mjc','title'=>'三码计重'],
				],
			],
			'kadu'=>[
				'title'=>'跨度',
				'list'=>[
					['playid'=>'kuaduqs','title'=>'前三跨度'],
					['playid'=>'kuaduzs','title'=>'中三跨度'],
					['playid'=>'kuaduhs','title'=>'后三跨度'],
					['playid'=>'kuaduqe','title'=>'前二跨度'],
					['playid'=>'kuaduhe','title'=>'后二跨度'],
				],
			],
			'rx'=>[
				'title'=>'任选',
				'list'=>[
					/*['playid'=>'rx4fs','title'=>'任四复式'],
					['playid'=>'rx4ds','title'=>'任四单式'],
					['playid'=>'rx3fs','title'=>'任三复式'],
					['playid'=>'rx3ds','title'=>'任三单式'],
					['playid'=>'rx3z3','title'=>'任三组三'],
					['playid'=>'rx3z6','title'=>'任三组六'],
					['playid'=>'rx3zxhh','title'=>'任三混合'],
					['playid'=>'rx2fs','title'=>'任二复式'],
					['playid'=>'rx2ds','title'=>'任二单式'],
					['playid'=>'rx2zx','title'=>'任二组选'],*/
				],
			],
			'dxds'=>[
				'title'=>'大小单双',
				'list'=>[
					['playid'=>'dxdsqs','rate'=>'3.4','title'=>'前三'],
					['playid'=>'dxdshs','rate'=>'3.4','title'=>'后三'],
					['playid'=>'dxdsqe','rate'=>'3.4','title'=>'前二'],
					['playid'=>'dxdshe','rate'=>'3.4','title'=>'后二'],
				],
			],
			'hz'=>[
				'title'=>'和值',
				'list'=>[
					['playid'=>'zhixhzqs','title'=>'前三直选和值'],
					['playid'=>'zhixhzzs','title'=>'中三直选和值'],
					['playid'=>'zhixhzhs','title'=>'后三直选和值'],
					['playid'=>'zhixhzqe','title'=>'前二直选和值'],
					['playid'=>'zhixhzhe','title'=>'后二直选和值'],
					['playid'=>'zuxhzqs','title'=>'前三组选和值'],
					['playid'=>'zuxhzzs','title'=>'中三组选和值'],
					['playid'=>'zuxhzhs','title'=>'后三组选和值'],
					['playid'=>'zuxhzqe','title'=>'前二组选和值'],
				    ['playid'=>'zuxhzhe','title'=>'后二组选和值'],
					['playid'=>'hzwsqs','title'=>'前三和尾'],
					['playid'=>'hzwszs','title'=>'中三和尾'],
					['playid'=>'hzwshs','title'=>'后三和尾'],
					['playid'=>'hzwsqe','title'=>'前二和尾'],
					['playid'=>'hzwshe','title'=>'后二和尾'],
				],
			],
			'quw'=>[
				'title'=>'趣味',
				'list'=>[
					['playid'=>'qwyffs','title'=>'一帆风顺'],
					['playid'=>'qwhscs','title'=>'好事成双'],
					['playid'=>'qwsxbx','title'=>'三星报喜'],
					['playid'=>'qwsjfc','title'=>'四季发财'],
					['playid'=>'lhwq','title'=>'龙虎万千'],
					['playid'=>'lhwb','title'=>'龙虎万百'],
					['playid'=>'lhws','title'=>'龙虎万十'],
					['playid'=>'lhwg','title'=>'龙虎万个'],
					['playid'=>'lhqb','title'=>'龙虎千百'],
					['playid'=>'lhqs','title'=>'龙虎千十'],
					['playid'=>'lhqg','title'=>'龙虎千个'],
					['playid'=>'lhbs','title'=>'龙虎百十'],
					['playid'=>'lhbg','title'=>'龙虎百个'],
					['playid'=>'lhsg','title'=>'龙虎十个'],
				],
			],
			'lhwq'=>[
				'title'=>'龙虎（趣味龙虎玩法以下面赔率为准）',
				'list'=>[
					['playid'=>'lhwql','title'=>'龙'],
					['playid'=>'lhwqhu','title'=>'虎'],
					['playid'=>'lhwqhe','title'=>'和'],
					

				],
			],
		];
		return $ssc;
	}
	function kl10f(){
		$sf = [
			'dwd'=>[
				'title'=>'定位胆',
				'list'=>[
					['playid'=>'kl10dwd1','title'=>'第一位'],
					['playid'=>'kl10dwd2','title'=>'第二位'],
					['playid'=>'kl10dwd3','title'=>'第三位'],
					['playid'=>'kl10dwd4','title'=>'第四位'],
					['playid'=>'kl10dwd5','title'=>'第五位'],
					['playid'=>'kl10dwd6','title'=>'第六位'],
					['playid'=>'kl10dwd7','title'=>'第七位'],
					['playid'=>'kl10dwd8','title'=>'第八位'],
				],
			],
			'rx'=>[
				'title'=>'任选',
				'list'=>[
					['playid'=>'kl10rx1z1','title'=>'一中一'],
					['playid'=>'kl10rx2z2','title'=>'二中二'],
					['playid'=>'kl10rx3z3','title'=>'三中三'],
					['playid'=>'kl10rx4z4','title'=>'四中四'],
					['playid'=>'kl10rx5z5','title'=>'五中五'],
				],
			],
			'dt'=>[
				'title'=>'胆拖',
				'list'=>[
					['playid'=>'kl10dt2z2','title'=>'二中二'],
					['playid'=>'kl10dt3z3','title'=>'三中三'],
					['playid'=>'kl10dt4z4','title'=>'四中四'],
					['playid'=>'kl10dt5z5','title'=>'五中五'],
				],
			],
			'x3'=>[
				'title'=>'三星',
				'list'=>[
					['playid'=>'kl10qszxfs','title'=>'前三直选'],
					['playid'=>'kl10hszxfs','title'=>'后三直选'],
					['playid'=>'kl10qszux','title'=>'前三组选'],
					['playid'=>'kl10hszux','title'=>'后三组选'],
				],
			],
			'x2'=>[
				'title'=>'二星',
				'list'=>[
					['playid'=>'kl10elzx','title'=>'二连直选'],
					['playid'=>'kl10elzux','title'=>'二连组选'],
				],
			],
		];
		return $sf;
	}
}
?>